Production image support including refactoring of build scripts

diff --git a/scripts/docker/install_packages b/scripts/docker/install_packages
--- a/scripts/docker/install_packages
+++ b/scripts/docker/install_packages
@@ -1,4 +1,4 @@
-#!/usr/bin/env bash
+#!/usr/bin/env sh
 # Licensed to the Apache Software Foundation (ASF) under one
 # or more contributor license agreements.  See the NOTICE file
 # distributed with this work for additional information
@@ -16,39 +16,29 @@
 # specific language governing permissions and limitations
 # under the License.
 
-set -euo pipefail
+# Bash sanity settings (error on exit, complain for undefined vars, error when pipe fails)
+set -euo
 
-MY_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
+. /etc/os-release
 
-export AIRFLOW_CI_SILENT=${AIRFLOW_CI_SILENT:="true"}
-
-# shellcheck source=scripts/ci/utils/_init.sh
-. "${MY_DIR}/utils/_init.sh"
-# shellcheck source=scripts/ci/utils/_build.sh
-. "${MY_DIR}/utils/_build.sh"
-# shellcheck source=scripts/ci/utils/_run.sh
-. "${MY_DIR}/utils/_run.sh"
-
-script_start
-
-initialize_environment
-
-prepare_build
-
-prepare_run
-
-rebuild_ci_slim_image_if_needed
-
-if [[ "${#@}" != "0" ]]; then
-    filter_out_files_from_pylint_todo_list "$@"
-
-    if [[ "${#FILTERED_FILES[@]}" == "0" ]]; then
-        echo "Filtered out all files. Skipping pylint."
-    else
-        run_pylint_tests "${FILTERED_FILES[@]}"
-    fi
+if [ "${ID}" = "debian" ]; then
+    echo
+    echo "Installing packages for Debian:" "$@"
+    echo
+    apt-get update \
+    && apt-get install -y --no-install-recommends \
+           "$@" \
+    && apt-get autoremove -yqq --purge \
+    && apt-get clean \
+    && rm -rf /var/lib/apt/lists/*
+elif [ "${ID}" = "alpine" ]; then
+    echo
+    echo "Installing packages for Alpine:" "$@"
+    echo
+    apk add --no-cache --virtual .build-deps "$@"
 else
-    run_pylint_tests
+    echo
+    echo "Exiting. The os ${ID} is unknown."
+    echo
+    exit 1
 fi
-
-script_end
