Faster testing

diff --git a/.github/workflows/build-images-workflow-run.yml b/.github/workflows/build-images-workflow-run.yml
--- a/.github/workflows/build-images-workflow-run.yml
+++ b/.github/workflows/build-images-workflow-run.yml
@@ -57,7 +57,7 @@ jobs:
     if: github.repository == 'apache/airflow' || github.event.workflow_run.event != 'schedule'
     steps:
       - name: "Cancel duplicated 'CI Build' runs"
-        uses: potiuk/cancel-workflow-runs@v2
+        uses: potiuk/cancel-workflow-runs@test-pr
         id: cancel
         with:
           token: ${{ secrets.GITHUB_TOKEN }}
@@ -201,99 +201,99 @@ jobs:
           initialization::ga_output all-python-versions \
               "$(initialization::parameters_to_json "${ALL_PYTHON_MAJOR_MINOR_VERSIONS[@]}")"
 
-  build-images:
-    timeout-minutes: 80
-    name: "Build ${{matrix.image-type}} images ${{matrix.python-version}}"
-    runs-on: ubuntu-latest
-    needs: [build-info, cancel-workflow-runs]
-    strategy:
-      matrix:
-      # We need to attempt to build all possible versions here because workflow_run
-      # event is run from master for both master and v1-10-tests
-        python-version: ${{ fromJson(needs.build-info.outputs.allPythonVersions) }}
-        image-type: [CI, PROD]
-      fail-fast: true
-    if: >
-      needs.cancel-workflow-runs.outputs.buildImages == 'true' &&
-      (github.repository == 'apache/airflow' || github.event.workflow_run.event != 'schedule')
-    env:
-      BACKEND: postgres
-      PYTHON_MAJOR_MINOR_VERSION: ${{ matrix.python-version }}
-      GITHUB_REGISTRY_PUSH_IMAGE_TAG: ${{ github.event.workflow_run.id }}
-      UPGRADE_TO_LATEST_CONSTRAINTS: ${{ needs.cancel-workflow-runs.outputs.upgradeToLatestConstraints }}
-      DOCKER_CACHE: ${{ needs.cancel-workflow-runs.outputs.cacheDirective }}
-    steps:
-      - name: >
-          Checkout [${{ needs.cancel-workflow-runs.outputs.sourceEvent }}]
-          Event: ${{ needs.cancel-workflow-runs.outputs.sourceEvent }}
-          Repo: ${{ needs.cancel-workflow-runs.outputs.sourceHeadRepo }}
-          Branch: ${{ needs.cancel-workflow-runs.outputs.sourceHeadBranch }}
-          Run id: ${{ github.run_id }}
-          Source Run id: ${{ github.event.workflow_run.id }}
-          Sha: ${{ github.sha }}
-          Source Sha: ${{ needs.cancel-workflow-runs.outputs.sourceHeadSha }}
-        uses: actions/checkout@v2
-        with:
-          ref: ${{ needs.cancel-workflow-runs.outputs.sourceHeadSha }}
-      - name: "Retrieve DEFAULTS from the _initialization.sh"
-        # We cannot "source" the script here because that would be a security problem (we cannot run
-        # any code that comes from the sources coming from the PR. Therefore we extract the
-        # DEFAULT_BRANCH and DEFAULT_CONSTRAINTS_BRANCH via custom grep/awk/sed commands
-        # Also 2.7 and 3.5 versions are not allowed to proceed on master
-        id: defaults
-        run: |
-          DEFAULT_BRANCH=$(grep "export DEFAULT_BRANCH" scripts/ci/libraries/_initialization.sh | \
-            awk 'BEGIN{FS="="} {print $3}' | sed s'/["}]//g')
-          echo "::set-env name=DEFAULT_BRANCH::${DEFAULT_BRANCH}"
-          DEFAULT_CONSTRAINTS_BRANCH=$(grep "export DEFAULT_CONSTRAINTS_BRANCH" \
-            scripts/ci/libraries/_initialization.sh | \
-            awk 'BEGIN{FS="="} {print $3}' | sed s'/["}]//g')
-          echo "::set-env name=DEFAULT_CONSTRAINTS_BRANCH::${DEFAULT_CONSTRAINTS_BRANCH}"
-          if [[ \
-            ${DEFAULT_BRANCH} != "master" || \
-            ( ${PYTHON_MAJOR_MINOR_VERSION} != "2.7" && ${PYTHON_MAJOR_MINOR_VERSION} != "3.5" ) \
-          ]]; then
-              echo "::set-output name=proceed::true"
-          else
-              echo "::set-output name=proceed::false"
-          fi
-      - name: "Checkout ${{ github.ref }} ( ${{ github.sha }} ) to 'main-airflow' to use main scripts"
-        uses: actions/checkout@v2
-        with:
-          path: "main-airflow"
-        if: steps.defaults.outputs.proceed == 'true'
-      - name: "Setup python"
-        uses: actions/setup-python@v2
-        with:
-          python-version: ${{ needs.build-info.outputs.defaultPythonVersion }}
-        if: steps.defaults.outputs.proceed == 'true'
-      - name: "Override 'scripts/ci' with the ${{ github.ref }} version so that the PR cannot override it."
-        # We should not override those scripts which become part of the image as they will not be
-        # changed in the image built - we should only override those that are executed to build
-        # the image.
-        run: |
-          rm -rf "scripts/ci"
-          mv "main-airflow/scripts/ci" "scripts"
-        if: steps.defaults.outputs.proceed == 'true'
-      - name: "Free space"
-        run: ./scripts/ci/tools/ci_free_space_on_ci.sh
-        if: steps.defaults.outputs.proceed == 'true'
-      - name: "Build CI images ${{ matrix.python-version }}:${{ github.event.workflow_run.id }}"
-        run: ./scripts/ci/images/ci_prepare_ci_image_on_ci.sh
-        if: matrix.image-type == 'CI' && steps.defaults.outputs.proceed == 'true'
-      - name: "Push CI images ${{ matrix.python-version }}:${{ github.event.workflow_run.id }}"
-        run: ./scripts/ci/images/ci_push_ci_images.sh
-        if: matrix.image-type == 'CI' && steps.defaults.outputs.proceed == 'true'
-      - name: "Build PROD images ${{ matrix.python-version }}:${{ github.event.workflow_run.id }}"
-        run: ./scripts/ci/images/ci_prepare_prod_image_on_ci.sh
-        if: matrix.image-type == 'PROD' && steps.defaults.outputs.proceed == 'true'
-      - name: "Push PROD images ${{ matrix.python-version }}:${{ github.event.workflow_run.id }}"
-        run: ./scripts/ci/images/ci_push_production_images.sh
-        if: matrix.image-type == 'PROD' && steps.defaults.outputs.proceed == 'true'
-      - name: "Canceling the CI Build source workflow in case of failure!"
-        if: cancelled() || failure()
-        uses: potiuk/cancel-workflow-runs@v2
-        with:
-          token: ${{ secrets.GITHUB_TOKEN }}
-          cancelMode: self
-          sourceRunId: ${{ github.event.workflow_run.id }}
+#  build-images:
+#    timeout-minutes: 80
+#    name: "Build ${{matrix.image-type}} images ${{matrix.python-version}}"
+#    runs-on: ubuntu-latest
+#    needs: [build-info, cancel-workflow-runs]
+#    strategy:
+#      matrix:
+#      # We need to attempt to build all possible versions here because workflow_run
+#      # event is run from master for both master and v1-10-tests
+#        python-version: ${{ fromJson(needs.build-info.outputs.allPythonVersions) }}
+#        image-type: [CI, PROD]
+#      fail-fast: true
+#    if: >
+#      needs.cancel-workflow-runs.outputs.buildImages == 'true' &&
+#      (github.repository == 'apache/airflow' || github.event.workflow_run.event != 'schedule')
+#    env:
+#      BACKEND: postgres
+#      PYTHON_MAJOR_MINOR_VERSION: ${{ matrix.python-version }}
+#      GITHUB_REGISTRY_PUSH_IMAGE_TAG: ${{ github.event.workflow_run.id }}
+#      UPGRADE_TO_LATEST_CONSTRAINTS: ${{ needs.cancel-workflow-runs.outputs.upgradeToLatestConstraints }}
+#      DOCKER_CACHE: ${{ needs.cancel-workflow-runs.outputs.cacheDirective }}
+#    steps:
+#      - name: >
+#          Checkout [${{ needs.cancel-workflow-runs.outputs.sourceEvent }}]
+#          Event: ${{ needs.cancel-workflow-runs.outputs.sourceEvent }}
+#          Repo: ${{ needs.cancel-workflow-runs.outputs.sourceHeadRepo }}
+#          Branch: ${{ needs.cancel-workflow-runs.outputs.sourceHeadBranch }}
+#          Run id: ${{ github.run_id }}
+#          Source Run id: ${{ github.event.workflow_run.id }}
+#          Sha: ${{ github.sha }}
+#          Source Sha: ${{ needs.cancel-workflow-runs.outputs.sourceHeadSha }}
+#        uses: actions/checkout@v2
+#        with:
+#          ref: ${{ needs.cancel-workflow-runs.outputs.sourceHeadSha }}
+#      - name: "Retrieve DEFAULTS from the _initialization.sh"
+#        # We cannot "source" the script here because that would be a security problem (we cannot run
+#        # any code that comes from the sources coming from the PR. Therefore we extract the
+#        # DEFAULT_BRANCH and DEFAULT_CONSTRAINTS_BRANCH via custom grep/awk/sed commands
+#        # Also 2.7 and 3.5 versions are not allowed to proceed on master
+#        id: defaults
+#        run: |
+#          DEFAULT_BRANCH=$(grep "export DEFAULT_BRANCH" scripts/ci/libraries/_initialization.sh | \
+#            awk 'BEGIN{FS="="} {print $3}' | sed s'/["}]//g')
+#          echo "::set-env name=DEFAULT_BRANCH::${DEFAULT_BRANCH}"
+#          DEFAULT_CONSTRAINTS_BRANCH=$(grep "export DEFAULT_CONSTRAINTS_BRANCH" \
+#            scripts/ci/libraries/_initialization.sh | \
+#            awk 'BEGIN{FS="="} {print $3}' | sed s'/["}]//g')
+#          echo "::set-env name=DEFAULT_CONSTRAINTS_BRANCH::${DEFAULT_CONSTRAINTS_BRANCH}"
+#          if [[ \
+#            ${DEFAULT_BRANCH} != "master" || \
+#            ( ${PYTHON_MAJOR_MINOR_VERSION} != "2.7" && ${PYTHON_MAJOR_MINOR_VERSION} != "3.5" ) \
+#          ]]; then
+#              echo "::set-output name=proceed::true"
+#          else
+#              echo "::set-output name=proceed::false"
+#          fi
+#      - name: "Checkout ${{ github.ref }} ( ${{ github.sha }} ) to 'main-airflow' to use main scripts"
+#        uses: actions/checkout@v2
+#        with:
+#          path: "main-airflow"
+#        if: steps.defaults.outputs.proceed == 'true'
+#      - name: "Setup python"
+#        uses: actions/setup-python@v2
+#        with:
+#          python-version: ${{ needs.build-info.outputs.defaultPythonVersion }}
+#        if: steps.defaults.outputs.proceed == 'true'
+#      - name: "Override 'scripts/ci' with the ${{ github.ref }} version so that the PR cannot override it."
+#        # We should not override those scripts which become part of the image as they will not be
+#        # changed in the image built - we should only override those that are executed to build
+#        # the image.
+#        run: |
+#          rm -rf "scripts/ci"
+#          mv "main-airflow/scripts/ci" "scripts"
+#        if: steps.defaults.outputs.proceed == 'true'
+#      - name: "Free space"
+#        run: ./scripts/ci/tools/ci_free_space_on_ci.sh
+#        if: steps.defaults.outputs.proceed == 'true'
+#      - name: "Build CI images ${{ matrix.python-version }}:${{ github.event.workflow_run.id }}"
+#        run: ./scripts/ci/images/ci_prepare_ci_image_on_ci.sh
+#        if: matrix.image-type == 'CI' && steps.defaults.outputs.proceed == 'true'
+#      - name: "Push CI images ${{ matrix.python-version }}:${{ github.event.workflow_run.id }}"
+#        run: ./scripts/ci/images/ci_push_ci_images.sh
+#        if: matrix.image-type == 'CI' && steps.defaults.outputs.proceed == 'true'
+#      - name: "Build PROD images ${{ matrix.python-version }}:${{ github.event.workflow_run.id }}"
+#        run: ./scripts/ci/images/ci_prepare_prod_image_on_ci.sh
+#        if: matrix.image-type == 'PROD' && steps.defaults.outputs.proceed == 'true'
+#      - name: "Push PROD images ${{ matrix.python-version }}:${{ github.event.workflow_run.id }}"
+#        run: ./scripts/ci/images/ci_push_production_images.sh
+#        if: matrix.image-type == 'PROD' && steps.defaults.outputs.proceed == 'true'
+#      - name: "Canceling the CI Build source workflow in case of failure!"
+#        if: cancelled() || failure()
+#        uses: potiuk/cancel-workflow-runs@v2
+#        with:
+#          token: ${{ secrets.GITHUB_TOKEN }}
+#          cancelMode: self
+#          sourceRunId: ${{ github.event.workflow_run.id }}
